//
//  Octicon.swift
//  iGithub
//
//  Created by Chan Hocheung on 7/20/16.
//  Copyright © 2016 Hocheung. All rights reserved.
//

import UIKit

enum Octicon : String, CustomStringConvertible {
    case Alert = "\u{f02d}"
    case ArrowDown = "\u{f03f}"
    case ArrowLeft = "\u{f040}"
    case ArrowRight = "\u{f03e}"
    case ArrowSmallDown = "\u{f0a0}"
    case ArrowSmallLeft = "\u{f0a1}"
    case ArrowSmallRight = "\u{f071}"
    case ArrowSmallUp = "\u{f09f}"
    case ArrowUp = "\u{f03d}"
    case Beaker = "\u{f0dd}"
    case Bell = "\u{f0de}"
    case Bold = "\u{f0e2}"
    case Book = "\u{f007}"
    case Bookmark = "\u{f07b}"
    case Briefcase = "\u{f0d3}"
    case Broadcast = "\u{f048}"
    case Browser = "\u{f0c5}"
    case Bug = "\u{f091}"
    case Calendar = "\u{f068}"
    case Check = "\u{f03a}"
    case Checklist = "\u{f076}"
    case ChevronDown = "\u{f0a3}"
    case ChevronLeft = "\u{f0a4}"
    case ChevronRight = "\u{f078}"
    case ChevronUp = "\u{f0a2}"
    case CircleSlash = "\u{f084}"
    case CircuitBoard = "\u{f0d6}"
    case Clippy = "\u{f035}"
    case Clock = "\u{f046}"
    case CloudDownload = "\u{f00b}"
    case CloudUpload = "\u{f00c}"
    case Code = "\u{f05f}"
    case CommentDiscussion = "\u{f04f}"
    case Comment = "\u{f02b}"
    case CreditCard = "\u{f045}"
    case Dash = "\u{f0ca}"
    case Dashboard = "\u{f07d}"
    case Database = "\u{f096}"
    case DesktopDownload = "\u{f0dc}"
    case DeviceCameraVideo = "\u{f057}"
    case DeviceCamera = "\u{f056}"
    case DeviceDesktop = "\u{f27c}"
    case DeviceMobile = "\u{f038}"
    case DiffAdded = "\u{f06b}"
    case DiffIgnored = "\u{f099}"
    case DiffModified = "\u{f06d}"
    case DiffRemoved = "\u{f06c}"
    case DiffRenamed = "\u{f06e}"
    case Diff = "\u{f04d}"
    case Ellipsis = "\u{f09a}"
    case Eye = "\u{f04e}"
    case FileBinary = "\u{f094}"
    case FileCode = "\u{f010}"
    case FileDirectory = "\u{f016}"
    case FileMedia = "\u{f012}"
    case FilePdf = "\u{f014}"
    case FileSubmodule = "\u{f017}"
    case FileSymlinkDirectory = "\u{f0b1}"
    case FileSymlinkFile = "\u{f0b0}"
    case FileText = "\u{f011}"
    case FileZip = "\u{f013}"
    case Flame = "\u{f0d2}"
    case Fold = "\u{f0cc}"
    case Gear = "\u{f02f}"
    case Gift = "\u{f042}"
    case GistSecret = "\u{f08c}"
    case Gist = "\u{f00e}"
    case GitBranch = "\u{f020}"
    case GitCommit = "\u{f01f}"
    case GitCompare = "\u{f0ac}"
    case GitMerge = "\u{f023}"
    case GitPullRequest = "\u{f009}"
    case Globe = "\u{f0b6}"
    case Graph = "\u{f043}"
    case Heart = "\u{2665}"
    case History = "\u{f07e}"
    case Home = "\u{f08d}"
    case HorizontalRule = "\u{f070}"
    case Hubot = "\u{f09d}"
    case Inbox = "\u{f0cf}"
    case Info = "\u{f059}"
    case IssueClosed = "\u{f028}"
    case IssueOpened = "\u{f026}"
    case IssueReopened = "\u{f027}"
    case Italic = "\u{f0e4}"
    case Jersey = "\u{f019}"
    case Key = "\u{f049}"
    case Keyboard = "\u{f00d}"
    case Law = "\u{f0d8}"
    case LightBulb = "\u{f000}"
    case LinkExternal = "\u{f07f}"
    case Link = "\u{f05c}"
    case ListOrdered = "\u{f062}"
    case ListUnordered = "\u{f061}"
    case Location = "\u{f060}"
    case Lock = "\u{f06a}"
    case LogoGist = "\u{f0ad}"
    case LogoGithub = "\u{f092}"
    case MailRead = "\u{f03c}"
    case MailReply = "\u{f051}"
    case Mail = "\u{f03b}"
    case MarkGithub = "\u{f00a}"
    case Markdown = "\u{f0c9}"
    case Megaphone = "\u{f077}"
    case Mention = "\u{f0be}"
    case Milestone = "\u{f075}"
    case Mirror = "\u{f024}"
    case MortarBoard = "\u{f0d7}"
    case Mute = "\u{f080}"
    case NoNewline = "\u{f09c}"
    case Octoface = "\u{f008}"
    case Organization = "\u{f037}"
    case Package = "\u{f0c4}"
    case Paintcan = "\u{f0d1}"
    case Pencil = "\u{f058}"
    case Person = "\u{f018}"
    case Pin = "\u{f041}"
    case Plug = "\u{f0d4}"
    case Plus = "\u{f05d}"
    case PrimitiveDot = "\u{f052}"
    case PrimitiveSquare = "\u{f053}"
    case Pulse = "\u{f085}"
    case Question = "\u{f02c}"
    case Quote = "\u{f063}"
    case RadioTower = "\u{f030}"
    case RepoClone = "\u{f04c}"
    case RepoForcePush = "\u{f04a}"
    case RepoForked = "\u{f002}"
    case RepoPull = "\u{f006}"
    case RepoPush = "\u{f005}"
    case Repo = "\u{f001}"
    case Rocket = "\u{f033}"
    case Rss = "\u{f034}"
    case Ruby = "\u{f047}"
    case Search = "\u{f02e}"
    case Server = "\u{f097}"
    case Settings = "\u{f07c}"
    case Shield = "\u{f0e1}"
    case SignIn = "\u{f036}"
    case SignOut = "\u{f032}"
    case Smiley = "\u{f0e7}"
    case Squirrel = "\u{f0b2}"
    case Star = "\u{f02a}"
    case Stop = "\u{f08f}"
    case Sync = "\u{f087}"
    case Tag = "\u{f015}"
    case Tasklist = "\u{f0e5}"
    case Telescope = "\u{f088}"
    case Terminal = "\u{f0c8}"
    case TextSize = "\u{f0e3}"
    case ThreeBars = "\u{f05e}"
    case Thumbsdown = "\u{f0db}"
    case Thumbsup = "\u{f0da}"
    case Tools = "\u{f031}"
    case Trashcan = "\u{f0d0}"
    case TriangleDown = "\u{f05b}"
    case TriangleLeft = "\u{f044}"
    case TriangleRight = "\u{f05a}"
    case TriangleUp = "\u{f0aa}"
    case Unfold = "\u{f039}"
    case Unmute = "\u{f0ba}"
    case Unverified = "\u{f0e8}"
    case Verified = "\u{f0e6}"
    case Versions = "\u{f064}"
    case Watch = "\u{f0e0}"
    case X = "\u{f081}"
    case Zap = "\u{26a1}"
    
    func iconString(text: String, fontSize: CGFloat = 14) -> NSAttributedString {
        
        let iconString = NSMutableAttributedString(string: "\(self)", attributes: [NSFontAttributeName: UIFont.OcticonOfSize(fontSize)])
        let attributedText = NSAttributedString(string: " \(text)", attributes: [NSFontAttributeName: UIFont.systemFontOfSize(fontSize)])
        
        iconString.appendAttributedString(attributedText)
        
        return iconString
    }
    
    var description : String {
        get {
            return self.rawValue
        }
    }
}

extension UIFont {
    @inline(__always) class func OcticonOfSize(fontSize: CGFloat) -> UIFont {
        return UIFont(name: "octicons", size: fontSize)!
    }
}
